### ISSUE TITLE
No matching export in "node-modules-polyfills:crypto" for import "X509Certificate"

### ISSUE THREAD

**Issue by Desttro** [agisboye/app-store-server-api#35]
I use a library with Cloudflare Workers:
```json
"devDependencies": {
  "@cloudflare/workers-types": "^4.20230904.0",
  "typescript": "^5.2.2",
  "wrangler": "^3.7.0"
}
```
when I run the application through the wrangler, it returns an error:
```zsh
✘ [ERROR] No matching export in "node-modules-polyfills:crypto" for import "X509Certificate"
 ../../node_modules/app-store-server-api/dist/esm/Decoding.js:37:9:
   37 │ import { X509Certificate } from "crypto";
      ╵          ~~~~~~~~~~~~~~~
✘ [ERROR] Failed to build
```
When I make the following changes, everything works as it should:
```ts
// src/Decoding.ts | 4 ++--

-import { X509Certificate } from "crypto"
+import * as crypto from "crypto"
 
-  const x509certs = certificates.map(c => new X509Certificate(c))
+  const x509certs = certificates.map(c => new crypto.X509Certificate(c))
```

**Comment by agisboye** [comment]
The Cloudflare Workers doesn't support the Node Crypto API (which is what this library uses). Instead it relies on the [Web Crypto API](https://developers.cloudflare.com/workers/runtime-apis/web-crypto/).

I'm surprised that you found your example to work since I can't find any reference stating that Web Crypto contains the `X509Certificate` class (or any other way of working with X509 certificates for that matter).

**Comment by agisboye** [comment]
That makes sense. It throws an error because `crypto.X509Certificate` is undefined. 😊 

I don't have any plans of adding support for Web Crypto. I'd prefer not to add any dependencies that are unnecessary for the majority of users of this library (those running Node.js). If you can come up with a solution I'm happy to take a look.

**Comment by saviourdog** [comment]
hi, @agisboye ,First of all, thank you for providing such a great plugin. However, there are increasingly more JavaScript runtime environments available today, such as Deno, Bun, and Cloudflare Workers, they may not necessarily support all the APIs of Node.js. Therefore, I would still appreciate it if you could support these platforms if you have the time. Thank you.

**Comment by agisboye** [comment]
Hi @saviourdog,

Thanks for using the library! I unfortunately don't have the time to add support for every new runtime that pops up. If you want to propose a solution for supporting other runtimes, I'd be happy to have a discussion around it.
